# Generated by Django 5.2.4 on 2025-08-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
    ]
