# Generated by Django 5.2.15 on 2026-07-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
